### ISSUE TITLE
node build_json.js not working anymore

### ISSUE THREAD

**Issue by Taelyn** [antihax/ATLAS-Extract-Plugin#2]
Error: ENOENT: no such file or directory, open 'DumpResources/server/ShooterGame/Binaries/Win64/resources/islandInfo.json'
    at Object.openSync (node:fs:592:3)
    at Object.readFileSync (node:fs:460:35)
    at Object.parseJSONFile (xxxx\atlastools\include\helpers.js:65:22)
    at Object.<anonymous> (xxxx\build_json.js:12:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'DumpResources/server/ShooterGame/Binaries/Win64/resources/islandInfo.json'
}

**Comment by antihax** [comment]
Fixed
