### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by dtmaster79** [antihax/ATLAS-Extract-Plugin#3]
Hi. I get this error displayed here.

E:\Downloads\ATLAS-Extract-Plugin-master\ATLAS-Extract-Plugin-master\build_json.js:203
                                islandPoints: islandInfo[cp.id] ? islandInfo[cp.id].islandPoints || 0 : 0
                                                        ^

TypeError: Cannot read properties of null (reading '11')
    at main (E:\Downloads\ATLAS-Extract-Plugin-master\ATLAS-Extract-Plugin-master\build_json.js:203:29)

**I ran it again with nobuild.**

E:\Downloads\ATLAS-Extract\ATLAS-Extract>node build_json.js nobuild
processing...
E:\Downloads\ATLAS-Extract\ATLAS-Extract\build_json.js:203
                                islandPoints: islandInfo[cp.id] ? islandInfo[cp.id].islandPoints || 0 : 0
                                                        ^

TypeError: Cannot read properties of null (reading '11')
    at main (E:\Downloads\ATLAS-Extract\ATLAS-Extract\build_json.js:203:29)
    at Object.<anonymous> (E:\Downloads\ATLAS-Extract\ATLAS-Extract\build_json.js:694:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.8.1

**Comment by ptepartz** [comment]
Did you figure this out? Just tried to run it again because we updated our map and I am getting a similar error.

Edit to add: The only issue I noticed while running is that some mods were not downloading due to an error. I compared mod folder to one I had on another disk and some only partly installed.
